// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sto.Repository.Core;

#nullable disable

namespace Sto.Repository.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20240612063612_Init_update_nullable0")]
    partial class Init_update_nullable0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sto.Repository.Entities.Store", b =>
                {
                    b.Property<long>("Uid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ClosingTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ClosingTime");

                    b.Property<double>("DeliveryPrice")
                        .HasColumnType("float")
                        .HasColumnName("DeliveryPrice");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit")
                        .HasColumnName("IsDelete");

                    b.Property<DateTime>("OpeningTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("OpeningTime");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Position");

                    b.Property<double>("Score")
                        .HasColumnType("float")
                        .HasColumnName("Score");

                    b.Property<double>("StartPrice")
                        .HasColumnType("float")
                        .HasColumnName("StartPrice");

                    b.Property<string>("StoreDesc")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("StoreDesc");

                    b.Property<byte[]>("StoreImage")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("StoreImage");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("StoreName");

                    b.HasKey("Uid")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.ToTable("Stores", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
